name: Pytest CI

on:
  push:
    branches:
      - version-15
  pull_request:
    branches:
      - version-15
  workflow_dispatch:
    inputs:
      user:
        description: "Frappe Framework repository user (add your username for forks)"
        required: true
        default: "frappe"
        type: string
      branch:
        description: "Frappe Framework branch"
        default: "version-15"
        required: false
        type: string

# concurrency:
#   group: develop-cloud_storage-${{ github.event.number }}
#   cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    name: Server

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MARIADB_ROOT_PASSWORD: "123"
        ports:
          - 3306:3306
        options: --health-cmd="mariadb-admin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check for valid Python & Merge Conflicts
        run: |
          python -m compileall -f "${GITHUB_WORKSPACE}"
          if grep -lr --exclude-dir=node_modules "^<<<<<<< " "${GITHUB_WORKSPACE}"
              then echo "Found merge conflicts"
              exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          check-latest: true

      - name: Add to Hosts
        run: echo "127.0.0.1 test_site" | sudo tee -a /etc/hosts

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt', '**/pyproject.toml', '**/setup.py', '**/setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Bench Site and Apps
        run: |
          bash ${GITHUB_WORKSPACE}/.github/workflows/helper/install.sh
        env:
          SITES: 1
          DB: mariadb
          TYPE: server
          APP_UNDER_TEST: "div_order_fulfillment"
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Setup Test Site and Fixtures
        run: |
          cd ~/frappe-bench
          source env/bin/activate
          python apps/frappe_devutils/frappe_devutils/tests/setup.py --site-number 1 --skip-switch

      - name: Run Tests
        run: |
          cd ~/frappe-bench
          source env/bin/activate
          pytest apps/frappe_devutils --disable-warnings -s
